
export interface CharacterType {
  ownerID:string,
  bonds:string,
  flaws:string,
  ideals:string,
  traits:string,
  castingClass:string,
  castingAbility:string,
  castingDC:number,
  castingBonus:number,
  spellSlots:[],
  name:string,
  race:string,
  languages:string,
  alignment:string,
  background:string,
  job:string,
  passivePerception:number,
  initiative:number,
  backstory:string,
  ac:number,
  inspiration:number,
  hp: {
    current:number,
    max:number,
    temp:number
  },
  exp:number,
  speed:number,
  items:[],
  feats:[],
  spells:[],
  armorProfs:string,
  weaponProfs:string,
  toolProfs:string,
  savingThrows: {
    charisma:boolean,
    constitution:boolean,
    dexterity:boolean,
    intelligence:boolean,
    strength:boolean,
    wisdom:boolean,
  },

  skills: {
    acrobatics:number,
    animalHandling:number,
    arcana:number,
    athletics:number,
    deception:number,
    history:number,
    insight:number,
    intimidation:number,
    investigation:number,
    medicine:number,
    nature:number,
    perception:number,
    performance:number,
    persuasion:number,
    religion:number,
    sleightOfHand:number,
    stealth:number,
    survival:number,
  },
  stats: {
    charisma:number,
    constitution:number,
    dexterity:number,
    intelligence:number,
    strength:number,
    wisdom:number
  },
  hitdice:string,
  deathsaves: {
    fails:number,
    success:number
  },
  createdAt:string
  updatedAt:string
}
